### ISSUE TITLE
Saltillo  missing from libertine

### ISSUE THREAD

**Issue by Glottotopia** [langsci/langsci-fonts#4]
Saltillos
http://www.fileformat.info/info/unicode/char/a78b/index.htm
http://www.fileformat.info/info/unicode/char/a78c/index.htm

Needed for Rapa Nui grammar

**Comment by somelinguist** [comment]
The orthographies of several languages in Mexico also use the saltillo to represent glottal stop or glottalized vowels. It would be helpful if this were included in the Libertine fonts, however, as far as I can tell, the fonts haven't been updated since 2012. So I'm not sure what would be the best way to go about using these characters in a publication that uses Libertine fonts,

**Comment by Glottotopia** [comment]
There is a workaround in https://github.com/langsci/langscibook/blob/master/langsci/styles/langsci-glyphs.sty with \saltillo and \Saltillo. It's the wrong font, but given the straight shape of the character, difference between fonts are not that great after all. It does survive c&p, which is central.

Also note that there is now the Libertinus project, which seems to be more responsive.

**Comment by somelinguist** [comment]
Thanks for the workaround. It's not ideal, given the proliferation of the saltillo in language data that uses it It will work though. I guess a preprocessor could be used to replace the Unicode characters with the workaround before compiling.

Are there many changes from Libertine to Libertinus? Do they look mostly the same?

**Comment by crysmann** [comment]
Libertinus is a fork from Libertine, and so is Libertine B (current LSP 
font).

Only feature that needs to be ported from Libertine B to Libertinus is 
diacritic placement.

Cheers,

B

**Comment by somelinguist** [comment]
@crysmann Thanks for the info. Is there a repo for the Libertine B font somewhere?
